name: Guatape
favicon: null
layout_spectrum: 0.6855868210550398
typography_spectrum: 0.6300124262925237
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2703810860402882
  lightness: 0.6555078676901758
  saturation: 0.06927408976480365
  rhythmicContrast: 0.7642439045011997
purpose: []
